import Head from 'next/head'
import styles from '../styles/Home.module.css'

import {createStore} from 'redux';
import {Provider} from 'react-redux';

import App from './components/App';
import rootReducer from './reducers';

const store = createStore(rootReducer);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <App />
    </Provider>
    </div>
  )
}
